CATALOGUE_HOST: catalogue.sureshdevops.online
USER_HOST: user.sureshdevops.online
SHIPPING_HOST: shipping.sureshdevops.online
CART_HOST: cart.sureshdevops.online
PAYMENT_HOST: payment.sureshdevops.online